mod error;
pub use error::Result;
mod server;
pub use server::{Server, app};
mod controllers;
mod repositories;
pub use repositories::link_repository::LinkRepository;
pub mod models;
mod config;
pub use config::Config;
pub mod auth;